wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715109587.0
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 3
      - 8
      - 13
      - 19
      - 23
      - 62
      4: 3.10.0
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 25
epochs:
  desc: null
  value: 100
